// ------------------------------
// 都道府県データ
// ------------------------------
const prefectures = [
  { name: "北海道", yomi: "ほっかいどう" },
  { name: "青森", yomi: "あおもり" },
  { name: "岩手", yomi: "いわて" },
  { name: "宮城", yomi: "みやぎ" },
  { name: "秋田", yomi: "あきた" },
  { name: "山形", yomi: "やまがた" },
  { name: "福島", yomi: "ふくしま" },
  { name: "茨城", yomi: "いばらき" },
  { name: "栃木", yomi: "とちぎ" },
  { name: "群馬", yomi: "ぐんま" },
  { name: "埼玉", yomi: "さいたま" },
  { name: "千葉", yomi: "ちば" },
  { name: "東京", yomi: "とうきょう" },
  { name: "神奈川", yomi: "かながわ" },
  { name: "新潟", yomi: "にいがた" },
  { name: "富山", yomi: "とやま" },
  { name: "石川", yomi: "いしかわ" },
  { name: "福井", yomi: "ふくい" },
  { name: "山梨", yomi: "やまなし" },
  { name: "長野", yomi: "ながの" },
  { name: "岐阜", yomi: "ぎふ" },
  { name: "静岡", yomi: "しずおか" },
  { name: "愛知", yomi: "あいち" },
  { name: "三重", yomi: "みえ" },
  { name: "滋賀", yomi: "しが" },
  { name: "京都", yomi: "きょうと" },
  { name: "大阪", yomi: "おおさか" },
  { name: "兵庫", yomi: "ひょうご" },
  { name: "奈良", yomi: "なら" },
  { name: "和歌山", yomi: "わかやま" },
  { name: "鳥取", yomi: "とっとり" },
  { name: "島根", yomi: "しまね" },
  { name: "岡山", yomi: "おかやま" },
  { name: "広島", yomi: "ひろしま" },
  { name: "山口", yomi: "やまぐち" },
  { name: "徳島", yomi: "とくしま" },
  { name: "香川", yomi: "かがわ" },
  { name: "愛媛", yomi: "えひめ" },
  { name: "高知", yomi: "こうち" },
  { name: "福岡", yomi: "ふくおか" },
  { name: "佐賀", yomi: "さが" },
  { name: "長崎", yomi: "ながさき" },
  { name: "熊本", yomi: "くまもと" },
  { name: "大分", yomi: "おおいた" },
  { name: "宮崎", yomi: "みやざき" },
  { name: "鹿児島", yomi: "かごしま" },
  { name: "沖縄", yomi: "おきなわ" }
];

const dowList = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];
